version: "3.3"

services: 
  mongo:
    image: mongo
    container_name: mongodb
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes: 
      - ./data:/data/db
  nodejs:
    image: "node:12"
    container_name: nodejs
    user: "node"
    env_file: ".env"
    working_dir: "/home/src/node/node-mongo"
    environment: 
      - MONGO_USERNAME=$MONGO_USERNAME
      - MONGO_PASSWORD=$MONGO_PASSWORD
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
    ports: 
      - "8000:8000"
    volumes:
      - .:/home/src/node/node-mongo
      - ./node_modules:/home/src/node/node-mongo/node_modules
    command: "npm run dev"
    depends_on: 
      - mongo
networks: 
  app-network:
    driver: bridge
